version: "3.7"
services:
  worker_peekaboo:
    image: dermaster/worker-peekaboo-dev:latest
    volumes:
      - type: bind
        source: .
        target: /go/src/worker-peekaboo
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      resources:
        limits:
         cpus: "1.0"
         memory: 1000M
    networks:
      - develop_network
networks:
  develop_network:
