// Code generated by protoc-gen-go. DO NOT EDIT.
// source: peekaboo.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PikabuRequest struct {
	Category             string   `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	Keyword              string   `protobuf:"bytes,10,opt,name=keyword,proto3" json:"keyword,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PikabuRequest) Reset()         { *m = PikabuRequest{} }
func (m *PikabuRequest) String() string { return proto.CompactTextString(m) }
func (*PikabuRequest) ProtoMessage()    {}
func (*PikabuRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e9296e1ca7b7ddb, []int{0}
}

func (m *PikabuRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PikabuRequest.Unmarshal(m, b)
}
func (m *PikabuRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PikabuRequest.Marshal(b, m, deterministic)
}
func (m *PikabuRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PikabuRequest.Merge(m, src)
}
func (m *PikabuRequest) XXX_Size() int {
	return xxx_messageInfo_PikabuRequest.Size(m)
}
func (m *PikabuRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PikabuRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PikabuRequest proto.InternalMessageInfo

func (m *PikabuRequest) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *PikabuRequest) GetKeyword() string {
	if m != nil {
		return m.Keyword
	}
	return ""
}

type PikabuReply struct {
	Category             string   `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PikabuReply) Reset()         { *m = PikabuReply{} }
func (m *PikabuReply) String() string { return proto.CompactTextString(m) }
func (*PikabuReply) ProtoMessage()    {}
func (*PikabuReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e9296e1ca7b7ddb, []int{1}
}

func (m *PikabuReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PikabuReply.Unmarshal(m, b)
}
func (m *PikabuReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PikabuReply.Marshal(b, m, deterministic)
}
func (m *PikabuReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PikabuReply.Merge(m, src)
}
func (m *PikabuReply) XXX_Size() int {
	return xxx_messageInfo_PikabuReply.Size(m)
}
func (m *PikabuReply) XXX_DiscardUnknown() {
	xxx_messageInfo_PikabuReply.DiscardUnknown(m)
}

var xxx_messageInfo_PikabuReply proto.InternalMessageInfo

func (m *PikabuReply) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

type RefreshWindowsRequest struct {
	Keyword              string   `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefreshWindowsRequest) Reset()         { *m = RefreshWindowsRequest{} }
func (m *RefreshWindowsRequest) String() string { return proto.CompactTextString(m) }
func (*RefreshWindowsRequest) ProtoMessage()    {}
func (*RefreshWindowsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e9296e1ca7b7ddb, []int{2}
}

func (m *RefreshWindowsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshWindowsRequest.Unmarshal(m, b)
}
func (m *RefreshWindowsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshWindowsRequest.Marshal(b, m, deterministic)
}
func (m *RefreshWindowsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshWindowsRequest.Merge(m, src)
}
func (m *RefreshWindowsRequest) XXX_Size() int {
	return xxx_messageInfo_RefreshWindowsRequest.Size(m)
}
func (m *RefreshWindowsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshWindowsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshWindowsRequest proto.InternalMessageInfo

func (m *RefreshWindowsRequest) GetKeyword() string {
	if m != nil {
		return m.Keyword
	}
	return ""
}

type RefreshWindowsReply struct {
	WindowList           []*RefreshWindowsReply_Window `protobuf:"bytes,1,rep,name=window_list,json=windowList,proto3" json:"window_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *RefreshWindowsReply) Reset()         { *m = RefreshWindowsReply{} }
func (m *RefreshWindowsReply) String() string { return proto.CompactTextString(m) }
func (*RefreshWindowsReply) ProtoMessage()    {}
func (*RefreshWindowsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e9296e1ca7b7ddb, []int{3}
}

func (m *RefreshWindowsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshWindowsReply.Unmarshal(m, b)
}
func (m *RefreshWindowsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshWindowsReply.Marshal(b, m, deterministic)
}
func (m *RefreshWindowsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshWindowsReply.Merge(m, src)
}
func (m *RefreshWindowsReply) XXX_Size() int {
	return xxx_messageInfo_RefreshWindowsReply.Size(m)
}
func (m *RefreshWindowsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshWindowsReply.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshWindowsReply proto.InternalMessageInfo

func (m *RefreshWindowsReply) GetWindowList() []*RefreshWindowsReply_Window {
	if m != nil {
		return m.WindowList
	}
	return nil
}

type RefreshWindowsReply_Window struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Handle               int32    `protobuf:"varint,2,opt,name=handle,proto3" json:"handle,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefreshWindowsReply_Window) Reset()         { *m = RefreshWindowsReply_Window{} }
func (m *RefreshWindowsReply_Window) String() string { return proto.CompactTextString(m) }
func (*RefreshWindowsReply_Window) ProtoMessage()    {}
func (*RefreshWindowsReply_Window) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e9296e1ca7b7ddb, []int{3, 0}
}

func (m *RefreshWindowsReply_Window) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshWindowsReply_Window.Unmarshal(m, b)
}
func (m *RefreshWindowsReply_Window) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshWindowsReply_Window.Marshal(b, m, deterministic)
}
func (m *RefreshWindowsReply_Window) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshWindowsReply_Window.Merge(m, src)
}
func (m *RefreshWindowsReply_Window) XXX_Size() int {
	return xxx_messageInfo_RefreshWindowsReply_Window.Size(m)
}
func (m *RefreshWindowsReply_Window) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshWindowsReply_Window.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshWindowsReply_Window proto.InternalMessageInfo

func (m *RefreshWindowsReply_Window) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *RefreshWindowsReply_Window) GetHandle() int32 {
	if m != nil {
		return m.Handle
	}
	return 0
}

type StartStreamingRequest struct {
	Handle               int32    `protobuf:"varint,1,opt,name=handle,proto3" json:"handle,omitempty"`
	Label                string   `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Quality              int32    `protobuf:"varint,3,opt,name=quality,proto3" json:"quality,omitempty"`
	Fps                  int32    `protobuf:"varint,4,opt,name=fps,proto3" json:"fps,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartStreamingRequest) Reset()         { *m = StartStreamingRequest{} }
func (m *StartStreamingRequest) String() string { return proto.CompactTextString(m) }
func (*StartStreamingRequest) ProtoMessage()    {}
func (*StartStreamingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e9296e1ca7b7ddb, []int{4}
}

func (m *StartStreamingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartStreamingRequest.Unmarshal(m, b)
}
func (m *StartStreamingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartStreamingRequest.Marshal(b, m, deterministic)
}
func (m *StartStreamingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartStreamingRequest.Merge(m, src)
}
func (m *StartStreamingRequest) XXX_Size() int {
	return xxx_messageInfo_StartStreamingRequest.Size(m)
}
func (m *StartStreamingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StartStreamingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StartStreamingRequest proto.InternalMessageInfo

func (m *StartStreamingRequest) GetHandle() int32 {
	if m != nil {
		return m.Handle
	}
	return 0
}

func (m *StartStreamingRequest) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *StartStreamingRequest) GetQuality() int32 {
	if m != nil {
		return m.Quality
	}
	return 0
}

func (m *StartStreamingRequest) GetFps() int32 {
	if m != nil {
		return m.Fps
	}
	return 0
}

type StartStreamingReply struct {
	Label                string   `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartStreamingReply) Reset()         { *m = StartStreamingReply{} }
func (m *StartStreamingReply) String() string { return proto.CompactTextString(m) }
func (*StartStreamingReply) ProtoMessage()    {}
func (*StartStreamingReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e9296e1ca7b7ddb, []int{5}
}

func (m *StartStreamingReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartStreamingReply.Unmarshal(m, b)
}
func (m *StartStreamingReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartStreamingReply.Marshal(b, m, deterministic)
}
func (m *StartStreamingReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartStreamingReply.Merge(m, src)
}
func (m *StartStreamingReply) XXX_Size() int {
	return xxx_messageInfo_StartStreamingReply.Size(m)
}
func (m *StartStreamingReply) XXX_DiscardUnknown() {
	xxx_messageInfo_StartStreamingReply.DiscardUnknown(m)
}

var xxx_messageInfo_StartStreamingReply proto.InternalMessageInfo

func (m *StartStreamingReply) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

type EndStreamingRequest struct {
	Handle               int32    `protobuf:"varint,1,opt,name=handle,proto3" json:"handle,omitempty"`
	Label                string   `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EndStreamingRequest) Reset()         { *m = EndStreamingRequest{} }
func (m *EndStreamingRequest) String() string { return proto.CompactTextString(m) }
func (*EndStreamingRequest) ProtoMessage()    {}
func (*EndStreamingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e9296e1ca7b7ddb, []int{6}
}

func (m *EndStreamingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EndStreamingRequest.Unmarshal(m, b)
}
func (m *EndStreamingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EndStreamingRequest.Marshal(b, m, deterministic)
}
func (m *EndStreamingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EndStreamingRequest.Merge(m, src)
}
func (m *EndStreamingRequest) XXX_Size() int {
	return xxx_messageInfo_EndStreamingRequest.Size(m)
}
func (m *EndStreamingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EndStreamingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EndStreamingRequest proto.InternalMessageInfo

func (m *EndStreamingRequest) GetHandle() int32 {
	if m != nil {
		return m.Handle
	}
	return 0
}

func (m *EndStreamingRequest) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

type EndStreamingReply struct {
	Handle               int32    `protobuf:"varint,1,opt,name=handle,proto3" json:"handle,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EndStreamingReply) Reset()         { *m = EndStreamingReply{} }
func (m *EndStreamingReply) String() string { return proto.CompactTextString(m) }
func (*EndStreamingReply) ProtoMessage()    {}
func (*EndStreamingReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e9296e1ca7b7ddb, []int{7}
}

func (m *EndStreamingReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EndStreamingReply.Unmarshal(m, b)
}
func (m *EndStreamingReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EndStreamingReply.Marshal(b, m, deterministic)
}
func (m *EndStreamingReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EndStreamingReply.Merge(m, src)
}
func (m *EndStreamingReply) XXX_Size() int {
	return xxx_messageInfo_EndStreamingReply.Size(m)
}
func (m *EndStreamingReply) XXX_DiscardUnknown() {
	xxx_messageInfo_EndStreamingReply.DiscardUnknown(m)
}

var xxx_messageInfo_EndStreamingReply proto.InternalMessageInfo

func (m *EndStreamingReply) GetHandle() int32 {
	if m != nil {
		return m.Handle
	}
	return 0
}

type ChangeQualityRequest struct {
	Quality              int32    `protobuf:"varint,1,opt,name=quality,proto3" json:"quality,omitempty"`
	Label                string   `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeQualityRequest) Reset()         { *m = ChangeQualityRequest{} }
func (m *ChangeQualityRequest) String() string { return proto.CompactTextString(m) }
func (*ChangeQualityRequest) ProtoMessage()    {}
func (*ChangeQualityRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e9296e1ca7b7ddb, []int{8}
}

func (m *ChangeQualityRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeQualityRequest.Unmarshal(m, b)
}
func (m *ChangeQualityRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeQualityRequest.Marshal(b, m, deterministic)
}
func (m *ChangeQualityRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeQualityRequest.Merge(m, src)
}
func (m *ChangeQualityRequest) XXX_Size() int {
	return xxx_messageInfo_ChangeQualityRequest.Size(m)
}
func (m *ChangeQualityRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeQualityRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeQualityRequest proto.InternalMessageInfo

func (m *ChangeQualityRequest) GetQuality() int32 {
	if m != nil {
		return m.Quality
	}
	return 0
}

func (m *ChangeQualityRequest) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

type ChangeQualityReply struct {
	Quality              int32    `protobuf:"varint,1,opt,name=quality,proto3" json:"quality,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeQualityReply) Reset()         { *m = ChangeQualityReply{} }
func (m *ChangeQualityReply) String() string { return proto.CompactTextString(m) }
func (*ChangeQualityReply) ProtoMessage()    {}
func (*ChangeQualityReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e9296e1ca7b7ddb, []int{9}
}

func (m *ChangeQualityReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeQualityReply.Unmarshal(m, b)
}
func (m *ChangeQualityReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeQualityReply.Marshal(b, m, deterministic)
}
func (m *ChangeQualityReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeQualityReply.Merge(m, src)
}
func (m *ChangeQualityReply) XXX_Size() int {
	return xxx_messageInfo_ChangeQualityReply.Size(m)
}
func (m *ChangeQualityReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeQualityReply.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeQualityReply proto.InternalMessageInfo

func (m *ChangeQualityReply) GetQuality() int32 {
	if m != nil {
		return m.Quality
	}
	return 0
}

type ChangeFpsRequest struct {
	Fps                  int32    `protobuf:"varint,1,opt,name=fps,proto3" json:"fps,omitempty"`
	Label                string   `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeFpsRequest) Reset()         { *m = ChangeFpsRequest{} }
func (m *ChangeFpsRequest) String() string { return proto.CompactTextString(m) }
func (*ChangeFpsRequest) ProtoMessage()    {}
func (*ChangeFpsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e9296e1ca7b7ddb, []int{10}
}

func (m *ChangeFpsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeFpsRequest.Unmarshal(m, b)
}
func (m *ChangeFpsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeFpsRequest.Marshal(b, m, deterministic)
}
func (m *ChangeFpsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeFpsRequest.Merge(m, src)
}
func (m *ChangeFpsRequest) XXX_Size() int {
	return xxx_messageInfo_ChangeFpsRequest.Size(m)
}
func (m *ChangeFpsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeFpsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeFpsRequest proto.InternalMessageInfo

func (m *ChangeFpsRequest) GetFps() int32 {
	if m != nil {
		return m.Fps
	}
	return 0
}

func (m *ChangeFpsRequest) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

type ChangeFpsReply struct {
	Fps                  int32    `protobuf:"varint,1,opt,name=fps,proto3" json:"fps,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeFpsReply) Reset()         { *m = ChangeFpsReply{} }
func (m *ChangeFpsReply) String() string { return proto.CompactTextString(m) }
func (*ChangeFpsReply) ProtoMessage()    {}
func (*ChangeFpsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e9296e1ca7b7ddb, []int{11}
}

func (m *ChangeFpsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeFpsReply.Unmarshal(m, b)
}
func (m *ChangeFpsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeFpsReply.Marshal(b, m, deterministic)
}
func (m *ChangeFpsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeFpsReply.Merge(m, src)
}
func (m *ChangeFpsReply) XXX_Size() int {
	return xxx_messageInfo_ChangeFpsReply.Size(m)
}
func (m *ChangeFpsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeFpsReply.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeFpsReply proto.InternalMessageInfo

func (m *ChangeFpsReply) GetFps() int32 {
	if m != nil {
		return m.Fps
	}
	return 0
}

type ChangePropertiesRequest struct {
	Handle               int32    `protobuf:"varint,1,opt,name=handle,proto3" json:"handle,omitempty"`
	Label                string   `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Quality              int32    `protobuf:"varint,3,opt,name=quality,proto3" json:"quality,omitempty"`
	Fps                  int32    `protobuf:"varint,4,opt,name=fps,proto3" json:"fps,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangePropertiesRequest) Reset()         { *m = ChangePropertiesRequest{} }
func (m *ChangePropertiesRequest) String() string { return proto.CompactTextString(m) }
func (*ChangePropertiesRequest) ProtoMessage()    {}
func (*ChangePropertiesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e9296e1ca7b7ddb, []int{12}
}

func (m *ChangePropertiesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangePropertiesRequest.Unmarshal(m, b)
}
func (m *ChangePropertiesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangePropertiesRequest.Marshal(b, m, deterministic)
}
func (m *ChangePropertiesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangePropertiesRequest.Merge(m, src)
}
func (m *ChangePropertiesRequest) XXX_Size() int {
	return xxx_messageInfo_ChangePropertiesRequest.Size(m)
}
func (m *ChangePropertiesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangePropertiesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChangePropertiesRequest proto.InternalMessageInfo

func (m *ChangePropertiesRequest) GetHandle() int32 {
	if m != nil {
		return m.Handle
	}
	return 0
}

func (m *ChangePropertiesRequest) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *ChangePropertiesRequest) GetQuality() int32 {
	if m != nil {
		return m.Quality
	}
	return 0
}

func (m *ChangePropertiesRequest) GetFps() int32 {
	if m != nil {
		return m.Fps
	}
	return 0
}

type ChangePropertiesReply struct {
	Label                string   `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangePropertiesReply) Reset()         { *m = ChangePropertiesReply{} }
func (m *ChangePropertiesReply) String() string { return proto.CompactTextString(m) }
func (*ChangePropertiesReply) ProtoMessage()    {}
func (*ChangePropertiesReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e9296e1ca7b7ddb, []int{13}
}

func (m *ChangePropertiesReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangePropertiesReply.Unmarshal(m, b)
}
func (m *ChangePropertiesReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangePropertiesReply.Marshal(b, m, deterministic)
}
func (m *ChangePropertiesReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangePropertiesReply.Merge(m, src)
}
func (m *ChangePropertiesReply) XXX_Size() int {
	return xxx_messageInfo_ChangePropertiesReply.Size(m)
}
func (m *ChangePropertiesReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangePropertiesReply.DiscardUnknown(m)
}

var xxx_messageInfo_ChangePropertiesReply proto.InternalMessageInfo

func (m *ChangePropertiesReply) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

type MouseDownRequest struct {
	Handle               int32    `protobuf:"varint,1,opt,name=handle,proto3" json:"handle,omitempty"`
	X                    float32  `protobuf:"fixed32,3,opt,name=x,proto3" json:"x,omitempty"`
	Y                    float32  `protobuf:"fixed32,4,opt,name=y,proto3" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MouseDownRequest) Reset()         { *m = MouseDownRequest{} }
func (m *MouseDownRequest) String() string { return proto.CompactTextString(m) }
func (*MouseDownRequest) ProtoMessage()    {}
func (*MouseDownRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e9296e1ca7b7ddb, []int{14}
}

func (m *MouseDownRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MouseDownRequest.Unmarshal(m, b)
}
func (m *MouseDownRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MouseDownRequest.Marshal(b, m, deterministic)
}
func (m *MouseDownRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MouseDownRequest.Merge(m, src)
}
func (m *MouseDownRequest) XXX_Size() int {
	return xxx_messageInfo_MouseDownRequest.Size(m)
}
func (m *MouseDownRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MouseDownRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MouseDownRequest proto.InternalMessageInfo

func (m *MouseDownRequest) GetHandle() int32 {
	if m != nil {
		return m.Handle
	}
	return 0
}

func (m *MouseDownRequest) GetX() float32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *MouseDownRequest) GetY() float32 {
	if m != nil {
		return m.Y
	}
	return 0
}

type MouseDownReply struct {
	Handle               int32    `protobuf:"varint,1,opt,name=handle,proto3" json:"handle,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MouseDownReply) Reset()         { *m = MouseDownReply{} }
func (m *MouseDownReply) String() string { return proto.CompactTextString(m) }
func (*MouseDownReply) ProtoMessage()    {}
func (*MouseDownReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e9296e1ca7b7ddb, []int{15}
}

func (m *MouseDownReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MouseDownReply.Unmarshal(m, b)
}
func (m *MouseDownReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MouseDownReply.Marshal(b, m, deterministic)
}
func (m *MouseDownReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MouseDownReply.Merge(m, src)
}
func (m *MouseDownReply) XXX_Size() int {
	return xxx_messageInfo_MouseDownReply.Size(m)
}
func (m *MouseDownReply) XXX_DiscardUnknown() {
	xxx_messageInfo_MouseDownReply.DiscardUnknown(m)
}

var xxx_messageInfo_MouseDownReply proto.InternalMessageInfo

func (m *MouseDownReply) GetHandle() int32 {
	if m != nil {
		return m.Handle
	}
	return 0
}

type MouseDown2Request struct {
	Handle               int32    `protobuf:"varint,1,opt,name=handle,proto3" json:"handle,omitempty"`
	X                    int32    `protobuf:"varint,3,opt,name=x,proto3" json:"x,omitempty"`
	Y                    int32    `protobuf:"varint,4,opt,name=y,proto3" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MouseDown2Request) Reset()         { *m = MouseDown2Request{} }
func (m *MouseDown2Request) String() string { return proto.CompactTextString(m) }
func (*MouseDown2Request) ProtoMessage()    {}
func (*MouseDown2Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e9296e1ca7b7ddb, []int{16}
}

func (m *MouseDown2Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MouseDown2Request.Unmarshal(m, b)
}
func (m *MouseDown2Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MouseDown2Request.Marshal(b, m, deterministic)
}
func (m *MouseDown2Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MouseDown2Request.Merge(m, src)
}
func (m *MouseDown2Request) XXX_Size() int {
	return xxx_messageInfo_MouseDown2Request.Size(m)
}
func (m *MouseDown2Request) XXX_DiscardUnknown() {
	xxx_messageInfo_MouseDown2Request.DiscardUnknown(m)
}

var xxx_messageInfo_MouseDown2Request proto.InternalMessageInfo

func (m *MouseDown2Request) GetHandle() int32 {
	if m != nil {
		return m.Handle
	}
	return 0
}

func (m *MouseDown2Request) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *MouseDown2Request) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

type MouseDown2Reply struct {
	Handle               int32    `protobuf:"varint,1,opt,name=handle,proto3" json:"handle,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MouseDown2Reply) Reset()         { *m = MouseDown2Reply{} }
func (m *MouseDown2Reply) String() string { return proto.CompactTextString(m) }
func (*MouseDown2Reply) ProtoMessage()    {}
func (*MouseDown2Reply) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e9296e1ca7b7ddb, []int{17}
}

func (m *MouseDown2Reply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MouseDown2Reply.Unmarshal(m, b)
}
func (m *MouseDown2Reply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MouseDown2Reply.Marshal(b, m, deterministic)
}
func (m *MouseDown2Reply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MouseDown2Reply.Merge(m, src)
}
func (m *MouseDown2Reply) XXX_Size() int {
	return xxx_messageInfo_MouseDown2Reply.Size(m)
}
func (m *MouseDown2Reply) XXX_DiscardUnknown() {
	xxx_messageInfo_MouseDown2Reply.DiscardUnknown(m)
}

var xxx_messageInfo_MouseDown2Reply proto.InternalMessageInfo

func (m *MouseDown2Reply) GetHandle() int32 {
	if m != nil {
		return m.Handle
	}
	return 0
}

type MouseUpRequest struct {
	Handle               int32    `protobuf:"varint,1,opt,name=handle,proto3" json:"handle,omitempty"`
	X                    float32  `protobuf:"fixed32,3,opt,name=x,proto3" json:"x,omitempty"`
	Y                    float32  `protobuf:"fixed32,4,opt,name=y,proto3" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MouseUpRequest) Reset()         { *m = MouseUpRequest{} }
func (m *MouseUpRequest) String() string { return proto.CompactTextString(m) }
func (*MouseUpRequest) ProtoMessage()    {}
func (*MouseUpRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e9296e1ca7b7ddb, []int{18}
}

func (m *MouseUpRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MouseUpRequest.Unmarshal(m, b)
}
func (m *MouseUpRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MouseUpRequest.Marshal(b, m, deterministic)
}
func (m *MouseUpRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MouseUpRequest.Merge(m, src)
}
func (m *MouseUpRequest) XXX_Size() int {
	return xxx_messageInfo_MouseUpRequest.Size(m)
}
func (m *MouseUpRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MouseUpRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MouseUpRequest proto.InternalMessageInfo

func (m *MouseUpRequest) GetHandle() int32 {
	if m != nil {
		return m.Handle
	}
	return 0
}

func (m *MouseUpRequest) GetX() float32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *MouseUpRequest) GetY() float32 {
	if m != nil {
		return m.Y
	}
	return 0
}

type MouseUpReply struct {
	Handle               int32    `protobuf:"varint,1,opt,name=handle,proto3" json:"handle,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MouseUpReply) Reset()         { *m = MouseUpReply{} }
func (m *MouseUpReply) String() string { return proto.CompactTextString(m) }
func (*MouseUpReply) ProtoMessage()    {}
func (*MouseUpReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e9296e1ca7b7ddb, []int{19}
}

func (m *MouseUpReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MouseUpReply.Unmarshal(m, b)
}
func (m *MouseUpReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MouseUpReply.Marshal(b, m, deterministic)
}
func (m *MouseUpReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MouseUpReply.Merge(m, src)
}
func (m *MouseUpReply) XXX_Size() int {
	return xxx_messageInfo_MouseUpReply.Size(m)
}
func (m *MouseUpReply) XXX_DiscardUnknown() {
	xxx_messageInfo_MouseUpReply.DiscardUnknown(m)
}

var xxx_messageInfo_MouseUpReply proto.InternalMessageInfo

func (m *MouseUpReply) GetHandle() int32 {
	if m != nil {
		return m.Handle
	}
	return 0
}

type MouseUp2Request struct {
	Handle               int32    `protobuf:"varint,1,opt,name=handle,proto3" json:"handle,omitempty"`
	X                    int32    `protobuf:"varint,3,opt,name=x,proto3" json:"x,omitempty"`
	Y                    int32    `protobuf:"varint,4,opt,name=y,proto3" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MouseUp2Request) Reset()         { *m = MouseUp2Request{} }
func (m *MouseUp2Request) String() string { return proto.CompactTextString(m) }
func (*MouseUp2Request) ProtoMessage()    {}
func (*MouseUp2Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e9296e1ca7b7ddb, []int{20}
}

func (m *MouseUp2Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MouseUp2Request.Unmarshal(m, b)
}
func (m *MouseUp2Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MouseUp2Request.Marshal(b, m, deterministic)
}
func (m *MouseUp2Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MouseUp2Request.Merge(m, src)
}
func (m *MouseUp2Request) XXX_Size() int {
	return xxx_messageInfo_MouseUp2Request.Size(m)
}
func (m *MouseUp2Request) XXX_DiscardUnknown() {
	xxx_messageInfo_MouseUp2Request.DiscardUnknown(m)
}

var xxx_messageInfo_MouseUp2Request proto.InternalMessageInfo

func (m *MouseUp2Request) GetHandle() int32 {
	if m != nil {
		return m.Handle
	}
	return 0
}

func (m *MouseUp2Request) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *MouseUp2Request) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

type MouseUp2Reply struct {
	Handle               int32    `protobuf:"varint,1,opt,name=handle,proto3" json:"handle,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MouseUp2Reply) Reset()         { *m = MouseUp2Reply{} }
func (m *MouseUp2Reply) String() string { return proto.CompactTextString(m) }
func (*MouseUp2Reply) ProtoMessage()    {}
func (*MouseUp2Reply) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e9296e1ca7b7ddb, []int{21}
}

func (m *MouseUp2Reply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MouseUp2Reply.Unmarshal(m, b)
}
func (m *MouseUp2Reply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MouseUp2Reply.Marshal(b, m, deterministic)
}
func (m *MouseUp2Reply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MouseUp2Reply.Merge(m, src)
}
func (m *MouseUp2Reply) XXX_Size() int {
	return xxx_messageInfo_MouseUp2Reply.Size(m)
}
func (m *MouseUp2Reply) XXX_DiscardUnknown() {
	xxx_messageInfo_MouseUp2Reply.DiscardUnknown(m)
}

var xxx_messageInfo_MouseUp2Reply proto.InternalMessageInfo

func (m *MouseUp2Reply) GetHandle() int32 {
	if m != nil {
		return m.Handle
	}
	return 0
}

type MouseMoveRequest struct {
	Handle               int32    `protobuf:"varint,1,opt,name=handle,proto3" json:"handle,omitempty"`
	X                    float32  `protobuf:"fixed32,3,opt,name=x,proto3" json:"x,omitempty"`
	Y                    float32  `protobuf:"fixed32,4,opt,name=y,proto3" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MouseMoveRequest) Reset()         { *m = MouseMoveRequest{} }
func (m *MouseMoveRequest) String() string { return proto.CompactTextString(m) }
func (*MouseMoveRequest) ProtoMessage()    {}
func (*MouseMoveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e9296e1ca7b7ddb, []int{22}
}

func (m *MouseMoveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MouseMoveRequest.Unmarshal(m, b)
}
func (m *MouseMoveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MouseMoveRequest.Marshal(b, m, deterministic)
}
func (m *MouseMoveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MouseMoveRequest.Merge(m, src)
}
func (m *MouseMoveRequest) XXX_Size() int {
	return xxx_messageInfo_MouseMoveRequest.Size(m)
}
func (m *MouseMoveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MouseMoveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MouseMoveRequest proto.InternalMessageInfo

func (m *MouseMoveRequest) GetHandle() int32 {
	if m != nil {
		return m.Handle
	}
	return 0
}

func (m *MouseMoveRequest) GetX() float32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *MouseMoveRequest) GetY() float32 {
	if m != nil {
		return m.Y
	}
	return 0
}

type MouseMoveReply struct {
	Handle               int32    `protobuf:"varint,1,opt,name=handle,proto3" json:"handle,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MouseMoveReply) Reset()         { *m = MouseMoveReply{} }
func (m *MouseMoveReply) String() string { return proto.CompactTextString(m) }
func (*MouseMoveReply) ProtoMessage()    {}
func (*MouseMoveReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e9296e1ca7b7ddb, []int{23}
}

func (m *MouseMoveReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MouseMoveReply.Unmarshal(m, b)
}
func (m *MouseMoveReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MouseMoveReply.Marshal(b, m, deterministic)
}
func (m *MouseMoveReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MouseMoveReply.Merge(m, src)
}
func (m *MouseMoveReply) XXX_Size() int {
	return xxx_messageInfo_MouseMoveReply.Size(m)
}
func (m *MouseMoveReply) XXX_DiscardUnknown() {
	xxx_messageInfo_MouseMoveReply.DiscardUnknown(m)
}

var xxx_messageInfo_MouseMoveReply proto.InternalMessageInfo

func (m *MouseMoveReply) GetHandle() int32 {
	if m != nil {
		return m.Handle
	}
	return 0
}

type MouseMove2Request struct {
	Handle               int32    `protobuf:"varint,1,opt,name=handle,proto3" json:"handle,omitempty"`
	X                    int32    `protobuf:"varint,3,opt,name=x,proto3" json:"x,omitempty"`
	Y                    int32    `protobuf:"varint,4,opt,name=y,proto3" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MouseMove2Request) Reset()         { *m = MouseMove2Request{} }
func (m *MouseMove2Request) String() string { return proto.CompactTextString(m) }
func (*MouseMove2Request) ProtoMessage()    {}
func (*MouseMove2Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e9296e1ca7b7ddb, []int{24}
}

func (m *MouseMove2Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MouseMove2Request.Unmarshal(m, b)
}
func (m *MouseMove2Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MouseMove2Request.Marshal(b, m, deterministic)
}
func (m *MouseMove2Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MouseMove2Request.Merge(m, src)
}
func (m *MouseMove2Request) XXX_Size() int {
	return xxx_messageInfo_MouseMove2Request.Size(m)
}
func (m *MouseMove2Request) XXX_DiscardUnknown() {
	xxx_messageInfo_MouseMove2Request.DiscardUnknown(m)
}

var xxx_messageInfo_MouseMove2Request proto.InternalMessageInfo

func (m *MouseMove2Request) GetHandle() int32 {
	if m != nil {
		return m.Handle
	}
	return 0
}

func (m *MouseMove2Request) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *MouseMove2Request) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

type MouseMove2Reply struct {
	Handle               int32    `protobuf:"varint,1,opt,name=handle,proto3" json:"handle,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MouseMove2Reply) Reset()         { *m = MouseMove2Reply{} }
func (m *MouseMove2Reply) String() string { return proto.CompactTextString(m) }
func (*MouseMove2Reply) ProtoMessage()    {}
func (*MouseMove2Reply) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e9296e1ca7b7ddb, []int{25}
}

func (m *MouseMove2Reply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MouseMove2Reply.Unmarshal(m, b)
}
func (m *MouseMove2Reply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MouseMove2Reply.Marshal(b, m, deterministic)
}
func (m *MouseMove2Reply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MouseMove2Reply.Merge(m, src)
}
func (m *MouseMove2Reply) XXX_Size() int {
	return xxx_messageInfo_MouseMove2Reply.Size(m)
}
func (m *MouseMove2Reply) XXX_DiscardUnknown() {
	xxx_messageInfo_MouseMove2Reply.DiscardUnknown(m)
}

var xxx_messageInfo_MouseMove2Reply proto.InternalMessageInfo

func (m *MouseMove2Reply) GetHandle() int32 {
	if m != nil {
		return m.Handle
	}
	return 0
}

func init() {
	proto.RegisterType((*PikabuRequest)(nil), "pb.PikabuRequest")
	proto.RegisterType((*PikabuReply)(nil), "pb.PikabuReply")
	proto.RegisterType((*RefreshWindowsRequest)(nil), "pb.RefreshWindowsRequest")
	proto.RegisterType((*RefreshWindowsReply)(nil), "pb.RefreshWindowsReply")
	proto.RegisterType((*RefreshWindowsReply_Window)(nil), "pb.RefreshWindowsReply.Window")
	proto.RegisterType((*StartStreamingRequest)(nil), "pb.StartStreamingRequest")
	proto.RegisterType((*StartStreamingReply)(nil), "pb.StartStreamingReply")
	proto.RegisterType((*EndStreamingRequest)(nil), "pb.EndStreamingRequest")
	proto.RegisterType((*EndStreamingReply)(nil), "pb.EndStreamingReply")
	proto.RegisterType((*ChangeQualityRequest)(nil), "pb.ChangeQualityRequest")
	proto.RegisterType((*ChangeQualityReply)(nil), "pb.ChangeQualityReply")
	proto.RegisterType((*ChangeFpsRequest)(nil), "pb.ChangeFpsRequest")
	proto.RegisterType((*ChangeFpsReply)(nil), "pb.ChangeFpsReply")
	proto.RegisterType((*ChangePropertiesRequest)(nil), "pb.ChangePropertiesRequest")
	proto.RegisterType((*ChangePropertiesReply)(nil), "pb.ChangePropertiesReply")
	proto.RegisterType((*MouseDownRequest)(nil), "pb.MouseDownRequest")
	proto.RegisterType((*MouseDownReply)(nil), "pb.MouseDownReply")
	proto.RegisterType((*MouseDown2Request)(nil), "pb.MouseDown2Request")
	proto.RegisterType((*MouseDown2Reply)(nil), "pb.MouseDown2Reply")
	proto.RegisterType((*MouseUpRequest)(nil), "pb.MouseUpRequest")
	proto.RegisterType((*MouseUpReply)(nil), "pb.MouseUpReply")
	proto.RegisterType((*MouseUp2Request)(nil), "pb.MouseUp2Request")
	proto.RegisterType((*MouseUp2Reply)(nil), "pb.MouseUp2Reply")
	proto.RegisterType((*MouseMoveRequest)(nil), "pb.MouseMoveRequest")
	proto.RegisterType((*MouseMoveReply)(nil), "pb.MouseMoveReply")
	proto.RegisterType((*MouseMove2Request)(nil), "pb.MouseMove2Request")
	proto.RegisterType((*MouseMove2Reply)(nil), "pb.MouseMove2Reply")
}

func init() { proto.RegisterFile("peekaboo.proto", fileDescriptor_4e9296e1ca7b7ddb) }

var fileDescriptor_4e9296e1ca7b7ddb = []byte{
	// 702 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0xdd, 0x6e, 0xd3, 0x4c,
	0x10, 0xd5, 0xa6, 0x5f, 0xd2, 0x76, 0xda, 0xa6, 0xc9, 0xa6, 0x69, 0x5d, 0x7f, 0x12, 0xaa, 0xf6,
	0x02, 0x52, 0x15, 0x82, 0x08, 0x02, 0x21, 0x2e, 0x40, 0xa8, 0x49, 0x90, 0x10, 0x95, 0x82, 0xab,
	0x8a, 0x4b, 0x64, 0x93, 0x6d, 0x62, 0xc5, 0xd8, 0x8e, 0xbd, 0x21, 0xf5, 0x4b, 0x20, 0xf1, 0xc6,
	0x68, 0xbd, 0xfe, 0x59, 0x3b, 0x8e, 0xa9, 0x94, 0x72, 0x97, 0x99, 0x9d, 0x39, 0x67, 0xc6, 0xb3,
	0x73, 0x36, 0x50, 0x77, 0x29, 0x9d, 0xe9, 0x86, 0xe3, 0x74, 0x5d, 0xcf, 0x61, 0x0e, 0xae, 0xb8,
	0x06, 0x19, 0xc0, 0xc1, 0xc8, 0x9c, 0xe9, 0xc6, 0x42, 0xa3, 0xf3, 0x05, 0xf5, 0x19, 0x56, 0x61,
	0xe7, 0xbb, 0xce, 0xe8, 0xc4, 0xf1, 0x02, 0x05, 0x9d, 0xa1, 0xce, 0xae, 0x96, 0xd8, 0x58, 0x81,
	0xed, 0x19, 0x0d, 0x96, 0x8e, 0x37, 0x56, 0x20, 0x3c, 0x8a, 0x4d, 0x72, 0x0e, 0x7b, 0x31, 0x8c,
	0x6b, 0x05, 0x65, 0x20, 0xe4, 0x05, 0xb4, 0x35, 0x7a, 0xeb, 0x51, 0x7f, 0xfa, 0xd5, 0xb4, 0xc7,
	0xce, 0xd2, 0x8f, 0x99, 0x25, 0x74, 0x94, 0x45, 0xff, 0x85, 0xa0, 0x95, 0xcf, 0xe1, 0x34, 0xef,
	0x61, 0x6f, 0x19, 0xda, 0xdf, 0x2c, 0xd3, 0x67, 0x0a, 0x3a, 0xdb, 0xea, 0xec, 0xf5, 0x1e, 0x75,
	0x5d, 0xa3, 0x5b, 0x10, 0xdd, 0x15, 0x86, 0x06, 0x22, 0xe5, 0xb3, 0xe9, 0x33, 0xf5, 0x35, 0xd4,
	0x84, 0x17, 0x1f, 0x41, 0x95, 0x99, 0xcc, 0xa2, 0x11, 0xb5, 0x30, 0xf0, 0x31, 0xd4, 0xa6, 0xba,
	0x3d, 0xb6, 0xa8, 0x52, 0x39, 0x43, 0x9d, 0xaa, 0x16, 0x59, 0x64, 0x0e, 0xed, 0x6b, 0xa6, 0x7b,
	0xec, 0x9a, 0x79, 0x54, 0xff, 0x61, 0xda, 0x93, 0xb8, 0x87, 0x34, 0x01, 0xc9, 0x09, 0x1c, 0xde,
	0xd2, 0x0d, 0x6a, 0x85, 0x38, 0xbb, 0x9a, 0x30, 0x78, 0xc7, 0xf3, 0x85, 0x6e, 0x99, 0x2c, 0x50,
	0xb6, 0xc2, 0xf0, 0xd8, 0xc4, 0x0d, 0xd8, 0xba, 0x75, 0x7d, 0xe5, 0xbf, 0xd0, 0xcb, 0x7f, 0x92,
	0x0b, 0x68, 0xe5, 0x29, 0xf9, 0x27, 0x48, 0x80, 0x91, 0x04, 0x4c, 0x2e, 0xa1, 0x35, 0xb0, 0xc7,
	0x9b, 0x55, 0x47, 0x2e, 0xa0, 0x99, 0x05, 0xe1, 0x7c, 0x6b, 0x20, 0xc8, 0x10, 0x8e, 0x2e, 0xa7,
	0xba, 0x3d, 0xa1, 0x5f, 0x44, 0x07, 0xd2, 0x50, 0xe3, 0x16, 0x51, 0xb6, 0xc5, 0x62, 0xd2, 0x2e,
	0xe0, 0x1c, 0x0e, 0x67, 0x5d, 0x8b, 0x42, 0xde, 0x42, 0x43, 0xc4, 0x0f, 0xdd, 0xe4, 0x22, 0x45,
	0x1f, 0x0f, 0x25, 0x1f, 0x6f, 0x0d, 0x17, 0x81, 0xba, 0x94, 0xcb, 0x79, 0x56, 0x32, 0x89, 0x0f,
	0x27, 0x22, 0x66, 0xe4, 0x39, 0x2e, 0xf5, 0x98, 0x49, 0xfd, 0x7f, 0x3f, 0xeb, 0x67, 0xd0, 0x5e,
	0x25, 0x5d, 0x3f, 0xed, 0x21, 0x34, 0xae, 0x9c, 0x85, 0x4f, 0xfb, 0xce, 0xd2, 0xfe, 0x5b, 0x71,
	0xfb, 0x80, 0xee, 0xc2, 0x02, 0x2a, 0x1a, 0xba, 0xe3, 0x56, 0x10, 0x12, 0x57, 0x34, 0x14, 0x90,
	0x0e, 0xd4, 0x25, 0x9c, 0xb2, 0x69, 0x7f, 0x84, 0x66, 0x12, 0xd9, 0xbb, 0x37, 0x65, 0x35, 0x43,
	0x59, 0xe5, 0x94, 0xe7, 0x70, 0x28, 0x03, 0x95, 0x71, 0xf6, 0xa3, 0xea, 0x6e, 0xdc, 0x4d, 0x7a,
	0x7c, 0x0c, 0xfb, 0x09, 0x4a, 0x19, 0xdb, 0x20, 0x2a, 0xec, 0xc6, 0xdd, 0xa8, 0xbf, 0x27, 0x70,
	0x90, 0xc2, 0x94, 0xef, 0x8f, 0x98, 0xe1, 0x95, 0xf3, 0x93, 0x3e, 0xc4, 0x0c, 0x05, 0xce, 0x7d,
	0x66, 0xc8, 0x23, 0x1f, 0x64, 0x86, 0x11, 0x50, 0x09, 0x67, 0xef, 0x77, 0x0d, 0x76, 0x46, 0xd1,
	0x23, 0x84, 0x9f, 0x42, 0x4d, 0xbc, 0x19, 0xb8, 0xc9, 0x25, 0x3b, 0xf3, 0x0c, 0xa9, 0x87, 0xb2,
	0x8b, 0x43, 0xf6, 0xa1, 0x9e, 0x15, 0x75, 0x7c, 0x5a, 0x24, 0xf4, 0x22, 0xfb, 0x64, 0xcd, 0x1b,
	0xc0, 0x51, 0xb2, 0x2a, 0x2a, 0x50, 0x0a, 0xc5, 0x5c, 0xa0, 0x14, 0x89, 0xee, 0x3b, 0xd8, 0x97,
	0x95, 0x11, 0x87, 0x81, 0x05, 0x82, 0xab, 0xb6, 0x57, 0x0f, 0x78, 0xfe, 0x07, 0x38, 0xc8, 0x88,
	0x1c, 0x56, 0x78, 0x5c, 0x91, 0x7e, 0xaa, 0xc7, 0x05, 0x27, 0x1c, 0xe2, 0x15, 0xec, 0x26, 0xda,
	0x85, 0x8f, 0xd2, 0xa0, 0x54, 0x06, 0x55, 0x9c, 0xf3, 0xf2, 0xb4, 0x4f, 0xb1, 0x5c, 0xa6, 0xca,
	0x82, 0xff, 0x4f, 0xe3, 0x56, 0x44, 0x4e, 0x3d, 0x2d, 0x3e, 0x8c, 0x4a, 0x48, 0x76, 0x57, 0x94,
	0x90, 0x57, 0x21, 0x51, 0x42, 0x4e, 0x53, 0xde, 0x00, 0xa4, 0x2b, 0x8f, 0xdb, 0x99, 0x88, 0xf8,
	0x1e, 0xaa, 0xad, 0xbc, 0x9b, 0x67, 0x3e, 0x87, 0xed, 0x68, 0x99, 0x70, 0x0a, 0x9c, 0xc8, 0x81,
	0xda, 0xc8, 0xf8, 0x78, 0x42, 0x0f, 0x76, 0xe2, 0xed, 0xc3, 0x2d, 0xe9, 0x34, 0xa1, 0x69, 0x66,
	0x9d, 0x72, 0x57, 0xfc, 0x36, 0x4b, 0x5d, 0x49, 0x7b, 0x29, 0x75, 0x95, 0x6e, 0x59, 0xdc, 0x55,
	0xb8, 0x04, 0x52, 0x57, 0xf2, 0x76, 0x49, 0x5d, 0xa5, 0xbb, 0x62, 0xd4, 0xc2, 0x3f, 0x63, 0x2f,
	0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0xb4, 0x7f, 0xfa, 0xe4, 0x9e, 0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PeekabooClient is the client API for Peekaboo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PeekabooClient interface {
	Pikabu(ctx context.Context, in *PikabuRequest, opts ...grpc.CallOption) (*PikabuReply, error)
	RefreshWindows(ctx context.Context, in *RefreshWindowsRequest, opts ...grpc.CallOption) (*RefreshWindowsReply, error)
	StartStreaming(ctx context.Context, in *StartStreamingRequest, opts ...grpc.CallOption) (*StartStreamingReply, error)
	EndStreaming(ctx context.Context, in *EndStreamingRequest, opts ...grpc.CallOption) (*EndStreamingReply, error)
	ChangeQuality(ctx context.Context, in *ChangeQualityRequest, opts ...grpc.CallOption) (*ChangeQualityReply, error)
	ChangeFps(ctx context.Context, in *ChangeFpsRequest, opts ...grpc.CallOption) (*ChangeFpsReply, error)
	ChangeProperties(ctx context.Context, in *ChangePropertiesRequest, opts ...grpc.CallOption) (*ChangePropertiesReply, error)
	MouseDown(ctx context.Context, in *MouseDownRequest, opts ...grpc.CallOption) (*MouseDownReply, error)
	MouseDown2(ctx context.Context, in *MouseDown2Request, opts ...grpc.CallOption) (*MouseDown2Reply, error)
	MouseUp(ctx context.Context, in *MouseUpRequest, opts ...grpc.CallOption) (*MouseUpReply, error)
	MouseUp2(ctx context.Context, in *MouseUp2Request, opts ...grpc.CallOption) (*MouseUp2Reply, error)
	MouseMove(ctx context.Context, in *MouseMoveRequest, opts ...grpc.CallOption) (*MouseMoveReply, error)
	MouseMove2(ctx context.Context, in *MouseMove2Request, opts ...grpc.CallOption) (*MouseMove2Reply, error)
}

type peekabooClient struct {
	cc *grpc.ClientConn
}

func NewPeekabooClient(cc *grpc.ClientConn) PeekabooClient {
	return &peekabooClient{cc}
}

func (c *peekabooClient) Pikabu(ctx context.Context, in *PikabuRequest, opts ...grpc.CallOption) (*PikabuReply, error) {
	out := new(PikabuReply)
	err := c.cc.Invoke(ctx, "/pb.Peekaboo/Pikabu", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peekabooClient) RefreshWindows(ctx context.Context, in *RefreshWindowsRequest, opts ...grpc.CallOption) (*RefreshWindowsReply, error) {
	out := new(RefreshWindowsReply)
	err := c.cc.Invoke(ctx, "/pb.Peekaboo/RefreshWindows", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peekabooClient) StartStreaming(ctx context.Context, in *StartStreamingRequest, opts ...grpc.CallOption) (*StartStreamingReply, error) {
	out := new(StartStreamingReply)
	err := c.cc.Invoke(ctx, "/pb.Peekaboo/StartStreaming", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peekabooClient) EndStreaming(ctx context.Context, in *EndStreamingRequest, opts ...grpc.CallOption) (*EndStreamingReply, error) {
	out := new(EndStreamingReply)
	err := c.cc.Invoke(ctx, "/pb.Peekaboo/EndStreaming", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peekabooClient) ChangeQuality(ctx context.Context, in *ChangeQualityRequest, opts ...grpc.CallOption) (*ChangeQualityReply, error) {
	out := new(ChangeQualityReply)
	err := c.cc.Invoke(ctx, "/pb.Peekaboo/ChangeQuality", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peekabooClient) ChangeFps(ctx context.Context, in *ChangeFpsRequest, opts ...grpc.CallOption) (*ChangeFpsReply, error) {
	out := new(ChangeFpsReply)
	err := c.cc.Invoke(ctx, "/pb.Peekaboo/ChangeFps", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peekabooClient) ChangeProperties(ctx context.Context, in *ChangePropertiesRequest, opts ...grpc.CallOption) (*ChangePropertiesReply, error) {
	out := new(ChangePropertiesReply)
	err := c.cc.Invoke(ctx, "/pb.Peekaboo/ChangeProperties", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peekabooClient) MouseDown(ctx context.Context, in *MouseDownRequest, opts ...grpc.CallOption) (*MouseDownReply, error) {
	out := new(MouseDownReply)
	err := c.cc.Invoke(ctx, "/pb.Peekaboo/MouseDown", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peekabooClient) MouseDown2(ctx context.Context, in *MouseDown2Request, opts ...grpc.CallOption) (*MouseDown2Reply, error) {
	out := new(MouseDown2Reply)
	err := c.cc.Invoke(ctx, "/pb.Peekaboo/MouseDown2", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peekabooClient) MouseUp(ctx context.Context, in *MouseUpRequest, opts ...grpc.CallOption) (*MouseUpReply, error) {
	out := new(MouseUpReply)
	err := c.cc.Invoke(ctx, "/pb.Peekaboo/MouseUp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peekabooClient) MouseUp2(ctx context.Context, in *MouseUp2Request, opts ...grpc.CallOption) (*MouseUp2Reply, error) {
	out := new(MouseUp2Reply)
	err := c.cc.Invoke(ctx, "/pb.Peekaboo/MouseUp2", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peekabooClient) MouseMove(ctx context.Context, in *MouseMoveRequest, opts ...grpc.CallOption) (*MouseMoveReply, error) {
	out := new(MouseMoveReply)
	err := c.cc.Invoke(ctx, "/pb.Peekaboo/MouseMove", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peekabooClient) MouseMove2(ctx context.Context, in *MouseMove2Request, opts ...grpc.CallOption) (*MouseMove2Reply, error) {
	out := new(MouseMove2Reply)
	err := c.cc.Invoke(ctx, "/pb.Peekaboo/MouseMove2", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PeekabooServer is the server API for Peekaboo service.
type PeekabooServer interface {
	Pikabu(context.Context, *PikabuRequest) (*PikabuReply, error)
	RefreshWindows(context.Context, *RefreshWindowsRequest) (*RefreshWindowsReply, error)
	StartStreaming(context.Context, *StartStreamingRequest) (*StartStreamingReply, error)
	EndStreaming(context.Context, *EndStreamingRequest) (*EndStreamingReply, error)
	ChangeQuality(context.Context, *ChangeQualityRequest) (*ChangeQualityReply, error)
	ChangeFps(context.Context, *ChangeFpsRequest) (*ChangeFpsReply, error)
	ChangeProperties(context.Context, *ChangePropertiesRequest) (*ChangePropertiesReply, error)
	MouseDown(context.Context, *MouseDownRequest) (*MouseDownReply, error)
	MouseDown2(context.Context, *MouseDown2Request) (*MouseDown2Reply, error)
	MouseUp(context.Context, *MouseUpRequest) (*MouseUpReply, error)
	MouseUp2(context.Context, *MouseUp2Request) (*MouseUp2Reply, error)
	MouseMove(context.Context, *MouseMoveRequest) (*MouseMoveReply, error)
	MouseMove2(context.Context, *MouseMove2Request) (*MouseMove2Reply, error)
}

// UnimplementedPeekabooServer can be embedded to have forward compatible implementations.
type UnimplementedPeekabooServer struct {
}

func (*UnimplementedPeekabooServer) Pikabu(ctx context.Context, req *PikabuRequest) (*PikabuReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Pikabu not implemented")
}
func (*UnimplementedPeekabooServer) RefreshWindows(ctx context.Context, req *RefreshWindowsRequest) (*RefreshWindowsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RefreshWindows not implemented")
}
func (*UnimplementedPeekabooServer) StartStreaming(ctx context.Context, req *StartStreamingRequest) (*StartStreamingReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartStreaming not implemented")
}
func (*UnimplementedPeekabooServer) EndStreaming(ctx context.Context, req *EndStreamingRequest) (*EndStreamingReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EndStreaming not implemented")
}
func (*UnimplementedPeekabooServer) ChangeQuality(ctx context.Context, req *ChangeQualityRequest) (*ChangeQualityReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangeQuality not implemented")
}
func (*UnimplementedPeekabooServer) ChangeFps(ctx context.Context, req *ChangeFpsRequest) (*ChangeFpsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangeFps not implemented")
}
func (*UnimplementedPeekabooServer) ChangeProperties(ctx context.Context, req *ChangePropertiesRequest) (*ChangePropertiesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangeProperties not implemented")
}
func (*UnimplementedPeekabooServer) MouseDown(ctx context.Context, req *MouseDownRequest) (*MouseDownReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MouseDown not implemented")
}
func (*UnimplementedPeekabooServer) MouseDown2(ctx context.Context, req *MouseDown2Request) (*MouseDown2Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MouseDown2 not implemented")
}
func (*UnimplementedPeekabooServer) MouseUp(ctx context.Context, req *MouseUpRequest) (*MouseUpReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MouseUp not implemented")
}
func (*UnimplementedPeekabooServer) MouseUp2(ctx context.Context, req *MouseUp2Request) (*MouseUp2Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MouseUp2 not implemented")
}
func (*UnimplementedPeekabooServer) MouseMove(ctx context.Context, req *MouseMoveRequest) (*MouseMoveReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MouseMove not implemented")
}
func (*UnimplementedPeekabooServer) MouseMove2(ctx context.Context, req *MouseMove2Request) (*MouseMove2Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MouseMove2 not implemented")
}

func RegisterPeekabooServer(s *grpc.Server, srv PeekabooServer) {
	s.RegisterService(&_Peekaboo_serviceDesc, srv)
}

func _Peekaboo_Pikabu_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PikabuRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeekabooServer).Pikabu(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Peekaboo/Pikabu",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeekabooServer).Pikabu(ctx, req.(*PikabuRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Peekaboo_RefreshWindows_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshWindowsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeekabooServer).RefreshWindows(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Peekaboo/RefreshWindows",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeekabooServer).RefreshWindows(ctx, req.(*RefreshWindowsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Peekaboo_StartStreaming_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartStreamingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeekabooServer).StartStreaming(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Peekaboo/StartStreaming",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeekabooServer).StartStreaming(ctx, req.(*StartStreamingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Peekaboo_EndStreaming_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EndStreamingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeekabooServer).EndStreaming(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Peekaboo/EndStreaming",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeekabooServer).EndStreaming(ctx, req.(*EndStreamingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Peekaboo_ChangeQuality_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeQualityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeekabooServer).ChangeQuality(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Peekaboo/ChangeQuality",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeekabooServer).ChangeQuality(ctx, req.(*ChangeQualityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Peekaboo_ChangeFps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeFpsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeekabooServer).ChangeFps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Peekaboo/ChangeFps",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeekabooServer).ChangeFps(ctx, req.(*ChangeFpsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Peekaboo_ChangeProperties_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangePropertiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeekabooServer).ChangeProperties(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Peekaboo/ChangeProperties",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeekabooServer).ChangeProperties(ctx, req.(*ChangePropertiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Peekaboo_MouseDown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MouseDownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeekabooServer).MouseDown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Peekaboo/MouseDown",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeekabooServer).MouseDown(ctx, req.(*MouseDownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Peekaboo_MouseDown2_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MouseDown2Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeekabooServer).MouseDown2(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Peekaboo/MouseDown2",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeekabooServer).MouseDown2(ctx, req.(*MouseDown2Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Peekaboo_MouseUp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MouseUpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeekabooServer).MouseUp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Peekaboo/MouseUp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeekabooServer).MouseUp(ctx, req.(*MouseUpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Peekaboo_MouseUp2_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MouseUp2Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeekabooServer).MouseUp2(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Peekaboo/MouseUp2",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeekabooServer).MouseUp2(ctx, req.(*MouseUp2Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Peekaboo_MouseMove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MouseMoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeekabooServer).MouseMove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Peekaboo/MouseMove",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeekabooServer).MouseMove(ctx, req.(*MouseMoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Peekaboo_MouseMove2_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MouseMove2Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeekabooServer).MouseMove2(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Peekaboo/MouseMove2",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeekabooServer).MouseMove2(ctx, req.(*MouseMove2Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _Peekaboo_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Peekaboo",
	HandlerType: (*PeekabooServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Pikabu",
			Handler:    _Peekaboo_Pikabu_Handler,
		},
		{
			MethodName: "RefreshWindows",
			Handler:    _Peekaboo_RefreshWindows_Handler,
		},
		{
			MethodName: "StartStreaming",
			Handler:    _Peekaboo_StartStreaming_Handler,
		},
		{
			MethodName: "EndStreaming",
			Handler:    _Peekaboo_EndStreaming_Handler,
		},
		{
			MethodName: "ChangeQuality",
			Handler:    _Peekaboo_ChangeQuality_Handler,
		},
		{
			MethodName: "ChangeFps",
			Handler:    _Peekaboo_ChangeFps_Handler,
		},
		{
			MethodName: "ChangeProperties",
			Handler:    _Peekaboo_ChangeProperties_Handler,
		},
		{
			MethodName: "MouseDown",
			Handler:    _Peekaboo_MouseDown_Handler,
		},
		{
			MethodName: "MouseDown2",
			Handler:    _Peekaboo_MouseDown2_Handler,
		},
		{
			MethodName: "MouseUp",
			Handler:    _Peekaboo_MouseUp_Handler,
		},
		{
			MethodName: "MouseUp2",
			Handler:    _Peekaboo_MouseUp2_Handler,
		},
		{
			MethodName: "MouseMove",
			Handler:    _Peekaboo_MouseMove_Handler,
		},
		{
			MethodName: "MouseMove2",
			Handler:    _Peekaboo_MouseMove2_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "peekaboo.proto",
}
